apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: error-pages-middleware
  namespace: error-pages
spec:
  errors:
    status:
      - "404"
    service:
      name: error-page
      port: 80
    query: /
---
# Ingress Default para qualquer domínio não mapeado (Catch-all)
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: catch-all
  namespace: error-pages
spec:
  entryPoints:
    - web
    - websecure
  routes:
    # Regra com prioridade 1 (a mais baixa possível) para pegar apenas o que sobrar
    - match: HostRegexp(`{host:.+}`)
      kind: Rule
      priority: 1
      services:
        - name: error-page
          port: 80
      middlewares:
        - name: error-pages-middleware
